// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFeedbackExportPath() {
  return window['go']['main']['App']['ChooseFeedbackExportPath']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearRequests() {
  return window['go']['main']['App']['ClearRequests']();
}

export function ConsoleInfo() {
  return window['go']['main']['App']['ConsoleInfo']();
}

export function ExportFeedbackBundle(arg1) {
  return window['go']['main']['App']['ExportFeedbackBundle'](arg1);
}

export function ExportServerDeploymentBundle(arg1) {
  return window['go']['main']['App']['ExportServerDeploymentBundle'](arg1);
}

export function ForceQuitApp() {
  return window['go']['main']['App']['ForceQuitApp']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetectionInfo() {
  return window['go']['main']['App']['GetDetectionInfo']();
}

export function GetLogDetail(arg1) {
  return window['go']['main']['App']['GetLogDetail'](arg1);
}

export function GetLogSummaries() {
  return window['go']['main']['App']['GetLogSummaries']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetRequestDetail(arg1) {
  return window['go']['main']['App']['GetRequestDetail'](arg1);
}

export function GetRequestSummaries() {
  return window['go']['main']['App']['GetRequestSummaries']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTokenStats() {
  return window['go']['main']['App']['GetTokenStats']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenPathInFileManager(arg1) {
  return window['go']['main']['App']['OpenPathInFileManager'](arg1);
}

export function RefreshModels() {
  return window['go']['main']['App']['RefreshModels']();
}

export function RequestQuitShortcut() {
  return window['go']['main']['App']['RequestQuitShortcut']();
}

export function SelectModel(arg1) {
  return window['go']['main']['App']['SelectModel'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
