// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {service} from '../models';

export function ChooseFeedbackExportPath():Promise<string>;

export function ClearLogs():Promise<void>;

export function ClearRequests():Promise<void>;

export function ConsoleInfo():Promise<main.ConsoleInfo>;

export function ExportFeedbackBundle(arg1:main.FeedbackExportOptions):Promise<main.FeedbackExportResult>;

export function ExportServerDeploymentBundle(arg1:main.ServerDeploymentExportOptions):Promise<main.ServerDeploymentExportResult>;

export function ForceQuitApp():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<service.Config>;

export function GetDetectionInfo():Promise<main.DetectionInfo>;

export function GetLogDetail(arg1:string):Promise<main.AppLog>;

export function GetLogSummaries():Promise<Array<main.AppLog>>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetRequestDetail(arg1:string):Promise<main.RequestRecord>;

export function GetRequestSummaries():Promise<Array<main.RequestRecord>>;

export function GetStatus():Promise<main.ProxyStatus>;

export function GetTokenStats():Promise<main.TokenStats>;

export function HideWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenPathInFileManager(arg1:string):Promise<void>;

export function RefreshModels():Promise<Array<main.ModelInfo>>;

export function RequestQuitShortcut():Promise<void>;

export function SelectModel(arg1:string):Promise<main.ProxyStatus>;

export function ShowWindow():Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;

export function UpdateConfig(arg1:service.Config):Promise<void>;
